apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-fpl-ui
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: k8.banterdo.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fpl-ui-service
            port:
              number: 80
